USE [master]
GO
/****** Object:  Database [Properties]    Script Date: 11/16/2023 6:57:13 AM ******/
CREATE DATABASE [Properties]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Properties', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\Properties.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Properties_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\Properties_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO
ALTER DATABASE [Properties] SET COMPATIBILITY_LEVEL = 160
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Properties].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [Properties] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [Properties] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [Properties] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [Properties] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [Properties] SET ARITHABORT OFF 
GO
ALTER DATABASE [Properties] SET AUTO_CLOSE ON 
GO
ALTER DATABASE [Properties] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [Properties] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [Properties] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [Properties] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [Properties] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [Properties] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [Properties] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [Properties] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [Properties] SET  ENABLE_BROKER 
GO
ALTER DATABASE [Properties] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [Properties] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [Properties] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [Properties] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [Properties] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [Properties] SET READ_COMMITTED_SNAPSHOT ON 
GO
ALTER DATABASE [Properties] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [Properties] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [Properties] SET  MULTI_USER 
GO
ALTER DATABASE [Properties] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [Properties] SET DB_CHAINING OFF 
GO
ALTER DATABASE [Properties] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [Properties] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [Properties] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [Properties] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
ALTER DATABASE [Properties] SET QUERY_STORE = ON
GO
ALTER DATABASE [Properties] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO
USE [Properties]
GO
/****** Object:  Table [dbo].[__EFMigrationsHistory]    Script Date: 11/16/2023 6:57:13 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[__EFMigrationsHistory](
	[MigrationId] [nvarchar](150) NOT NULL,
	[ProductVersion] [nvarchar](32) NOT NULL,
 CONSTRAINT [PK___EFMigrationsHistory] PRIMARY KEY CLUSTERED 
(
	[MigrationId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Owners]    Script Date: 11/16/2023 6:57:13 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Owners](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Name] [nvarchar](max) NOT NULL,
	[Address] [nvarchar](max) NOT NULL,
	[Photo] [varbinary](max) NOT NULL,
	[Birthday] [datetime2](7) NOT NULL,
 CONSTRAINT [PK_Owners] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Properties]    Script Date: 11/16/2023 6:57:13 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Properties](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Name] [nvarchar](max) NOT NULL,
	[Address] [nvarchar](max) NOT NULL,
	[Price] [real] NOT NULL,
	[CodeInternal] [nvarchar](max) NOT NULL,
	[Year] [int] NOT NULL,
	[OwnerId] [int] NULL,
 CONSTRAINT [PK_Properties] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[PropertyImages]    Script Date: 11/16/2023 6:57:13 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PropertyImages](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[File] [varbinary](max) NOT NULL,
	[Enabled] [bit] NOT NULL,
	[PropertyId] [int] NOT NULL,
 CONSTRAINT [PK_PropertyImages] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[PropertyTraces]    Script Date: 11/16/2023 6:57:13 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PropertyTraces](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[DateSale] [datetime2](7) NOT NULL,
	[Name] [nvarchar](max) NOT NULL,
	[Value] [real] NOT NULL,
	[Tax] [real] NOT NULL,
	[PropertyId] [int] NOT NULL,
 CONSTRAINT [PK_PropertyTraces] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Users]    Script Date: 11/16/2023 6:57:13 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Users](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Email] [nvarchar](max) NOT NULL,
	[Password] [nvarchar](max) NOT NULL,
 CONSTRAINT [PK_Users] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Index [IX_Properties_OwnerId]    Script Date: 11/16/2023 6:57:13 AM ******/
CREATE NONCLUSTERED INDEX [IX_Properties_OwnerId] ON [dbo].[Properties]
(
	[OwnerId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
/****** Object:  Index [IX_PropertyImages_PropertyId]    Script Date: 11/16/2023 6:57:13 AM ******/
CREATE NONCLUSTERED INDEX [IX_PropertyImages_PropertyId] ON [dbo].[PropertyImages]
(
	[PropertyId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
/****** Object:  Index [IX_PropertyTraces_PropertyId]    Script Date: 11/16/2023 6:57:13 AM ******/
CREATE NONCLUSTERED INDEX [IX_PropertyTraces_PropertyId] ON [dbo].[PropertyTraces]
(
	[PropertyId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Properties]  WITH CHECK ADD  CONSTRAINT [FK_Properties_Owners_OwnerId] FOREIGN KEY([OwnerId])
REFERENCES [dbo].[Owners] ([Id])
GO
ALTER TABLE [dbo].[Properties] CHECK CONSTRAINT [FK_Properties_Owners_OwnerId]
GO
ALTER TABLE [dbo].[PropertyImages]  WITH CHECK ADD  CONSTRAINT [FK_PropertyImages_Properties_PropertyId] FOREIGN KEY([PropertyId])
REFERENCES [dbo].[Properties] ([Id])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[PropertyImages] CHECK CONSTRAINT [FK_PropertyImages_Properties_PropertyId]
GO
ALTER TABLE [dbo].[PropertyTraces]  WITH CHECK ADD  CONSTRAINT [FK_PropertyTraces_Properties_PropertyId] FOREIGN KEY([PropertyId])
REFERENCES [dbo].[Properties] ([Id])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[PropertyTraces] CHECK CONSTRAINT [FK_PropertyTraces_Properties_PropertyId]
GO
USE [master]
GO
ALTER DATABASE [Properties] SET  READ_WRITE 
GO
